# All available Hugo versions are listed here: https://gitlab.com/pages/hugo/container_registry
image: registry.gitlab.com/pages/hugo/hugo_extended:0.59.1

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - deploy


test:
  stage: build
  script:
  - hugo
  except:
    - master

pages:
  stage: build
  script:
  - hugo
  artifacts:
    paths:
    - public
  only:
    - master
  
deploy-index:
  image: node:latest
  stage: deploy
  dependencies:
    - pages
  script:
    - npm install --save  atomic-algolia
    - node deploy-algolia-index.js
  only:
    - master
   

