# All available Hugo versions are listed here: https://gitlab.com/pages/hugo/container_registry
# Using specific images, cause the community image does support git. 
# To update the image, checkout the registry branch.
image: registry.gitlab.com/ecad-wiki/ecad-wiki.gitlab.io/hugo_extended:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - deploy


test:
  stage: build
  script:
  - hugo
  except:
    - master

pages:
  stage: build
  script:
  - hugo
  artifacts:
    paths:
    - public
  only:
    - master
  
deploy-index:
  image: node:latest
  stage: deploy
  dependencies:
    - pages
  script:
    - npm install --save  atomic-algolia
    - node deploy-algolia-index.js
  when: manual
  only:
    - master
   

