# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#vec"
  weight = 10

[[main]]
  name = "News"
  url = "news"
  weight = 20

[[main]]
  name = "Specifications"
  weight = 15

[[main]]
  name = "Vehicle Electric Container (VEC)"
  url = "specifications/vec"
  weight = 10
  parent = "Specifications"

[[main]]
  name = "Kabelbaumliste (KBL)"
  url = "specifications/kbl"
  weight = 20
  parent = "Specifications"

[[main]]
  name = "KOMP"
  url = "specifications/komp"
  weight = 90
  parent = "Specifications"
