# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#vec"
  weight = 10

[[main]]
  name = "News"
  url = "news"
  weight = 50

[[main]]
  name = "Archive"
  weight = 100

[[main]]
  name = "Vehicle Electric Container (VEC)"
  url = "specifications/vec"
  weight = 20

[[main]]
  name = "Kabelbaumliste (KBL)"
  url = "specifications/kbl"
  weight = 30
  
[[main]]
  name = "ELOG"
  url = "specifications/elog"
  weight = 70
  parent = "Archive"

[[main]]
  name = "GEO"
  url = "specifications/geo"
  weight = 80
  parent = "Archive"

  [[main]]
  name = "KOMP"
  url = "specifications/komp"
  weight = 90
  parent = "Archive"